name: Bug Report
description: Submit a bug report.
title: "[BUG]"
labels: ["bug"]
assignees:
  - eomasters-repos
body:
  - type: input
    id: title
    attributes:
      label: Title
      description: "Provide a short and descriptive title for the issue."
      placeholder: "Enter a brief title for the bug"
    validations:
      required: true

  - type: checkboxes
    id: used_software
    attributes:
      label: Used Software
      description: "Select the software you were using when the issue occurred."
      options:
        - label: DAVALIEN
        - label: EOMasters Pro Toolbox
        - label: EOMasters Basic Toolbox

  - type: textarea
    id: description
    attributes:
      label: Short Description
      description: "Summarize the issue in a few sentences."
      placeholder: "Enter a short description of the issue"
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce the Problem
      description: "Provide the necessary steps to reproduce the issue."
      placeholder: |
        For example:
        1. Step one
        2. Step two
        3. Step three
    validations:
      required: true

  - type: input
    id: operating_system
    attributes:
      label: Operating System
      description: "Specify the operating system you were using."
      placeholder: "e.g., Windows 11, macOS Ventura, Ubuntu 22.04"
    validations:
      required: true

  - type: markdown
    attributes:
      value: "Thanks for completing our form!"
