name: Feature Request
description: Submit a feature or enhancement request.
labels: [ "feature" ]
assignees:
  - eomasters-repos
body:

  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Describe your feature request."
      placeholder: |
        Include include your use case and what should be achieved by this feature. Describe steps how you would like to
        use the feature. Mention tools which already have a similar feature. All this helps to understand your requirement.
    validations:
      required: true

  - type: dropdown
    id: used_software
    attributes:
      label: Used Software
      description: "Select the software you were using when the issue occurred."
      options:
        - DAVALIEN
        - EOMasters Pro Toolbox
        - EOMasters Basic Toolbox
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce the Problem
      description: "Provide the necessary steps to reproduce the issue."
      placeholder: |
        For example:
        1. Step one
        2. Step two
        3. Step three

  - type: markdown
    attributes:
      value: "# Thanks for your request! We'll take care of it."
